// <auto-generated />
using System;
using Learn2CodeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Learn2CodeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210824130944_cs")]
    partial class cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "02174cf0–9412–4cfe - afbf - 59f706d72cf6"
                        });
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContentType");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseSubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("CourseSubCategoryId");

                    b.ToTable("CourseContent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("CourseFolderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("courseFolders");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseFolderId")
                        .HasColumnType("int");

                    b.Property<string>("CourseSubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseFolderId");

                    b.ToTable("courseSubCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DegreeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DegreeId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SessionContentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("SessionContentCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("SessionContentCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SessionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("SessionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SessionType");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SubscriptionTutorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("TutorSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TutorSessionId");

                    b.ToTable("SubscriptionTutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.TutorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SessionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionTypeId");

                    b.ToTable("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.TutorSessionModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("TutorSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TutorSessionId");

                    b.ToTable("TutorSessionModule");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("University");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Login.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "02174cf0–9412–4cfe - afbf - 59f706d72cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39be417b-4dde-4773-aead-e5f438bf3741",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEGp5c4joYnH4U+XOTJoqrFDR2+VjIsNwFWKFlI+EQ5m9YtVmvXDrWwh4Nl4jXNaT4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b9ecd93-d3ba-4578-a592-735338ce50aa",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.CourseEnrolLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseEnrolId")
                        .HasColumnType("int");

                    b.Property<int>("CourseSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrolId");

                    b.HasIndex("CourseSubCategoryId");

                    b.ToTable("CourseEnrolLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.EnrolLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("TicketQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("EnrolLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ability")
                        .HasColumnType("int");

                    b.Property<int>("BookingInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Friendliness")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Timliness")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingInstanceId");

                    b.HasIndex("StudentId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.StudentModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentModule");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.SubScriptionBasketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubScriptionBasketLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnrolLineId")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("int");

                    b.Property<int>("TutorSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrolLineId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TicketStatusId");

                    b.HasIndex("TutorSessionId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ticketStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.BookingInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AttendanceTaken")
                        .HasColumnType("bit");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("ContentUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("SessionTimeId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("TutorSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SessionTimeId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TutorId");

                    b.HasIndex("TutorSessionId");

                    b.ToTable("BookingInstance");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.BookingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bookingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookingStatus");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.CourseBasketLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("CourseSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("CourseSubCategoryId");

                    b.ToTable("CourseBasketLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.CourseEnrol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrol");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("FileName")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.GroupSessionContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookingInstanceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Notes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NotesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Recording")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RecordingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionContentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingInstanceId");

                    b.HasIndex("SessionContentCategoryId");

                    b.ToTable("GroupSessionContent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageSent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.RegisteredStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("BookingInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingInstanceId");

                    b.HasIndex("StudentId");

                    b.ToTable("RegisteredStudent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ResoucesName")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ResourceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ResourceCategoryId");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.ResourceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResourceCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.SessionTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SessionTime");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("TutorAbout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TutorCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TutorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TutorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("TutorPhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TutorStatusId")
                        .HasColumnType("int");

                    b.Property<string>("TutorSurname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TutorStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorModule");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorSessionModuleTutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("TutorSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TutorId");

                    b.HasIndex("TutorSessionId");

                    b.ToTable("TutorSessionModuleTutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TutorStatusDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TutorStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Admin", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", "Identity")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseContent", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.ContentType", "ContentType")
                        .WithMany("CourseContent")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.CourseSubCategory", "CourseSubCategory")
                        .WithMany("CourseContent")
                        .HasForeignKey("CourseSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("CourseSubCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseFolder", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Admin", "admin")
                        .WithMany("courseFolder")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseSubCategory", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.CourseFolder", "courseFolder")
                        .WithMany()
                        .HasForeignKey("CourseFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courseFolder");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Degree", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.University", "University")
                        .WithMany("Degree")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Module", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Degree", "Degree")
                        .WithMany("Module")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SessionContentCategory", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Subscription", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SubscriptionTutorSession", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Subscription", "Subscription")
                        .WithMany("SubscriptionTutorSession")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.TutorSession", "TutorSession")
                        .WithMany("SubscriptionTutorSession")
                        .HasForeignKey("TutorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.TutorSession", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.SessionType", "SessionType")
                        .WithMany("TutorSession")
                        .HasForeignKey("SessionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionType");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.TutorSessionModule", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("TutorSessionModule")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.TutorSession", "TutorSession")
                        .WithMany("TutorSessionModule")
                        .HasForeignKey("TutorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Booking", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany("Booking")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.CourseEnrolLine", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.CourseEnrol", "CourseEnrol")
                        .WithMany("CourseEnrolLine")
                        .HasForeignKey("CourseEnrolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.CourseSubCategory", "CourseSubCategory")
                        .WithMany("CourseEnrolLine")
                        .HasForeignKey("CourseSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseEnrol");

                    b.Navigation("CourseSubCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.EnrolLine", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Enrollment", "Enrollment")
                        .WithMany("EnrolLine")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("EnrolLine")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Subscription", "Subscription")
                        .WithMany("EnrolLine")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Module");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Enrollment", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Feedback", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.BookingInstance", "BookingInstance")
                        .WithMany("Feedback")
                        .HasForeignKey("BookingInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany("Feedback")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingInstance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Student", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", "Identity")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.StudentModule", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("StudentModule")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Students")
                        .WithMany("StudentModule")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.SubScriptionBasketLine", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.Basket", "Basket")
                        .WithMany("SubScriptionBasketLine")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("SubScriptionBasketLine")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Subscription", "Subscription")
                        .WithMany("SubScriptionBasketLine")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Module");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Ticket", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.EnrolLine", "EnrolLine")
                        .WithMany("Ticket")
                        .HasForeignKey("EnrolLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.Enrollment", "Enrollment")
                        .WithMany("Ticket")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("Ticket")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Subscription", "Subscription")
                        .WithMany("Ticket")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.TicketStatus", "TicketStatus")
                        .WithMany("Ticket")
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.TutorSession", "TutorSession")
                        .WithMany("Ticket")
                        .HasForeignKey("TutorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnrolLine");

                    b.Navigation("Enrollment");

                    b.Navigation("Module");

                    b.Navigation("Subscription");

                    b.Navigation("TicketStatus");

                    b.Navigation("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Basket", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.BookingInstance", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Booking", "Booking")
                        .WithMany("bookinginstances")
                        .HasForeignKey("BookingId");

                    b.HasOne("Learn2CodeAPI.Models.Tutor.BookingStatus", "BookingStatus")
                        .WithMany("BookingInstance")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("BookingInstance")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.SessionTime", "SessionTime")
                        .WithMany("BookingInstance")
                        .HasForeignKey("SessionTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId");

                    b.HasOne("Learn2CodeAPI.Models.Tutor.Tutor", "Tutor")
                        .WithMany("BookingInstance")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.TutorSession", "TutorSession")
                        .WithMany("BookingInstance")
                        .HasForeignKey("TutorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("BookingStatus");

                    b.Navigation("Module");

                    b.Navigation("SessionTime");

                    b.Navigation("Ticket");

                    b.Navigation("Tutor");

                    b.Navigation("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.CourseBasketLine", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.Basket", "Basket")
                        .WithMany("CourseBasketLine")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.CourseSubCategory", "CourseSubCategory")
                        .WithMany("CourseBasketLine")
                        .HasForeignKey("CourseSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("CourseSubCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.CourseEnrol", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany("CourseEnrol")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.GroupSessionContent", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.BookingInstance", "BookingInstance")
                        .WithMany()
                        .HasForeignKey("BookingInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.SessionContentCategory", "SessionContentCategory")
                        .WithMany("GroupSessionContent")
                        .HasForeignKey("SessionContentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingInstance");

                    b.Navigation("SessionContentCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Message", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "student")
                        .WithMany("message")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.Tutor", "tutor")
                        .WithMany("message")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("tutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.RegisteredStudent", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.BookingInstance", "BookingInstance")
                        .WithMany("RegisteredStudent")
                        .HasForeignKey("BookingInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Student.Student", "Student")
                        .WithMany("RegisteredStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingInstance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Resource", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("Resource")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.ResourceCategory", "ResourceCategory")
                        .WithMany("Resource")
                        .HasForeignKey("ResourceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("ResourceCategory");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Tutor", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Tutor.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.TutorStatus", "TutorStatus")
                        .WithMany("Tutors")
                        .HasForeignKey("TutorStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", "Identity")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("File");

                    b.Navigation("Identity");

                    b.Navigation("TutorStatus");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorModule", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("TutorModule")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.Tutor", "Tutor")
                        .WithMany("TutorModule")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorSessionModuleTutor", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Admin.Module", "Module")
                        .WithMany("TutorSessionModuleTutor")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Tutor.Tutor", "Tutor")
                        .WithMany("TutorSessionModuleTutor")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Admin.TutorSession", "TutorTutorSession")
                        .WithMany("TutorSessionModuleTutor")
                        .HasForeignKey("TutorSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Tutor");

                    b.Navigation("TutorTutorSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Learn2CodeAPI.Models.Login.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Admin", b =>
                {
                    b.Navigation("courseFolder");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.ContentType", b =>
                {
                    b.Navigation("CourseContent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.CourseSubCategory", b =>
                {
                    b.Navigation("CourseBasketLine");

                    b.Navigation("CourseContent");

                    b.Navigation("CourseEnrolLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Degree", b =>
                {
                    b.Navigation("Module");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Module", b =>
                {
                    b.Navigation("BookingInstance");

                    b.Navigation("EnrolLine");

                    b.Navigation("Resource");

                    b.Navigation("StudentModule");

                    b.Navigation("SubScriptionBasketLine");

                    b.Navigation("Ticket");

                    b.Navigation("TutorModule");

                    b.Navigation("TutorSessionModule");

                    b.Navigation("TutorSessionModuleTutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SessionContentCategory", b =>
                {
                    b.Navigation("GroupSessionContent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.SessionType", b =>
                {
                    b.Navigation("TutorSession");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.Subscription", b =>
                {
                    b.Navigation("EnrolLine");

                    b.Navigation("SubScriptionBasketLine");

                    b.Navigation("SubscriptionTutorSession");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.TutorSession", b =>
                {
                    b.Navigation("BookingInstance");

                    b.Navigation("SubscriptionTutorSession");

                    b.Navigation("Ticket");

                    b.Navigation("TutorSessionModule");

                    b.Navigation("TutorSessionModuleTutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Admin.University", b =>
                {
                    b.Navigation("Degree");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Booking", b =>
                {
                    b.Navigation("bookinginstances");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.EnrolLine", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Enrollment", b =>
                {
                    b.Navigation("EnrolLine");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.Student", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("CourseEnrol");

                    b.Navigation("Feedback");

                    b.Navigation("message");

                    b.Navigation("RegisteredStudent");

                    b.Navigation("StudentModule");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Student.TicketStatus", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Basket", b =>
                {
                    b.Navigation("CourseBasketLine");

                    b.Navigation("SubScriptionBasketLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.BookingInstance", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("RegisteredStudent");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.BookingStatus", b =>
                {
                    b.Navigation("BookingInstance");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.CourseEnrol", b =>
                {
                    b.Navigation("CourseEnrolLine");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.ResourceCategory", b =>
                {
                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.SessionTime", b =>
                {
                    b.Navigation("BookingInstance");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.Tutor", b =>
                {
                    b.Navigation("BookingInstance");

                    b.Navigation("message");

                    b.Navigation("TutorModule");

                    b.Navigation("TutorSessionModuleTutor");
                });

            modelBuilder.Entity("Learn2CodeAPI.Models.Tutor.TutorStatus", b =>
                {
                    b.Navigation("Tutors");
                });
#pragma warning restore 612, 618
        }
    }
}
